### ISSUE TITLE
Quick Stats Graph shows the current day twice

### ISSUE THREAD

**Issue by MausGames** [gamejolt/issue-tracker#329]
![quick](https://cloud.githubusercontent.com/assets/6109189/8624874/6ad9255c-273b-11e5-9f96-dbdba251284d.png)

I guess he is showing real-time stats for the current day, but there may also be some wrong calculations, so I wanted to mention it. (also it looks weird)

**Firefox 39.0**

**Comment by Tricky1975** [comment]
It this fixed now?
![image](https://cloud.githubusercontent.com/assets/11202073/9834250/ff98f24a-59b2-11e5-982b-26f99d25aca3.png)

(By the way, at the time this shot was taken I also saw everything being correct in the issue described in #358, which I believe confirms these two issues are indeed connected).

**Comment by MausGames** [comment]
After you posted this, I looked too and it was gone ...
... but now it's still there, so it's not yet fixed and probably depends on the current time.

**Comment by Tricky1975** [comment]
Yeah, I was thinking that was possible too, and I was about to check today. The picture you see was shot nearly 1am (in Central European Time).

**Comment by hworld** [comment]
Should now be fixed.
