### ISSUE TITLE
Chat messages some times don't prime when you click into a new chat room.

### ISSUE THREAD

**Issue by NickRock** [gamejolt/issue-tracker#354]
I don't know how to explain this one but it happens almost every time I open a chatroom
![chat_bug](https://cloud.githubusercontent.com/assets/11754980/9193223/8975cfcc-401a-11e5-8c3b-8696be2bf2d0.PNG)

**Comment by YLivay** [comment]
Ahhh the classic "You are now chatting with god"  bug. We know of it, not much to do with it now, will be solved when chat gets a recode probably haha.

**Comment by acidpoison** [comment]
I've gotten it too, but only a few times. Closing it and reopening it fixes it for me.

**Comment by Tricky1975** [comment]
Am I a moron for not understanding the issue?

**Comment by acidpoison** [comment]
@Tricky1975 When you open chat, its supposed to load about 30 messages to fill up the chat. The bug is that sometimes it only loads one, hence the image.

**Comment by Tricky1975** [comment]
Aha.... Now I get it... I guess I never noticed those 30 messages as I rarely (almost never) use the group chat.

**Comment by YLivay** [comment]
Will be fixed when chat gets a recode

**Comment by hworld** [comment]
Should be fixed in new chat.

**Comment by NickRock** [comment]
And still not fixed it happened today. Had to close and re-open the chat but I don't think we can't do much about it. Maybe it's because of the bad internet connection.

**Comment by YLivay** [comment]
Can you describe in more detail how it didnt work?
Exactly step by step.

**Comment by NickRock** [comment]
Yes.
First I clicked to the lobby chat, when the chat box opened there weren't any massages visible and when I sent a message nobody received it.

**Comment by YLivay** [comment]
Sounds like the UI let you open the room but the server didnt verify you can even join the room. Might've been a db spike when you tried or a stale connection.

Try using the chat with js console open. When it happens send us the log.

**Comment by YLivay** [comment]
Its a problem with not properly reestablishing connection to chat after losing connection.

**Comment by Agrosis** [comment]
Any screenshots for when this happens?

**Comment by YLivay** [comment]
Looks like the old chat room messages. This is how the console looks like:
![console log](http://i.imgur.com/vDk9eKL.png)

This is how the chatroom looks like:
![stuck chat](http://i.imgur.com/yEI1nYw.png)

If I let it wait an absurd amount of time (about 1 minute) it actually attempts to reconnect the spark for the first time and you can see spark-open in the log. but going online I think  should immediately trigger that check.

If the chat room was closed while  you had no  connection you could still maximize the window by clicking on it in the tab. Expected behaviour is either not opening it or repriming it as soon as that pink disconnected message goes away.

**Comment by YLivay** [comment]
lol look at that chat. This is sort of solved by the new behaviour where the chat window just disappears and reopens when the connection is re-established. Kind of sucks but it's a different issue now. More about UX. Closing this because we'll  probably change everything around when we do the new chat functionalities UI anyways.
