### ISSUE TITLE
My client got stuck with a game "Currently playing".

### ISSUE THREAD

**Issue by edwoodgrant** [gamejolt/issue-tracker#488]
Hello!

Reporting a bug here. I installed a couple of games in the GameJolt client. The first one was "Infinite Monkey Autocorrect". I played for a while, then exited. But the client got stuck with a bar down below showing "Currently Playing: Infinite Monkey Autocorrect".

Restarting the client won't remove the message. I cannot remove the game either because it thinks its currently playing. And cannot launch other games (I can donwload them and install them, but cannot launch them).

I double checked the Task manager and there is no InfiniteMonkeyAutocorrect.exe running.

I even restarted the whole OS, relaunched the client again to no avail. I also deleted the game from the installed games folder. Unfortunately it didn't work. The game still shows and it keeps saying I'm playing it.

I am using Windows 10. Here are some screenshots of the issue. Hope you can sort this out.

![gjcl_issue1](https://cloud.githubusercontent.com/assets/7331031/12250007/cde3f9c8-b891-11e5-9eda-b221797c3a3e.png)

![gjcl_issue2](https://cloud.githubusercontent.com/assets/7331031/12250002/c22ae95c-b891-11e5-993d-22edb496404a.png)

**Comment by hworld** [comment]
Hey, Edwood. We actually had just released a new version of Client that was supposed to fix this bug right around the time you posted this. Is there any way to see if it's fixed now? Client should've auto-updated itself if was connected to the Internet and has been running.

**Comment by edwoodgrant** [comment]
Hello!

I've just launched the client and yes, the client stopped saying I was "Currently playing something".
However the game still says that I'm still running it.

I was able to launch another game. I played Super crate box to test, and when I got out the same thing happened to that game. Cannot launch it again or uninstall it. However I can launch or uninstall other games. But everytime I launch a new game. It gets "stuck" in that same werid state that says its currently being run and cannot uninstall it.

So now I have like 6 games in the same weird limbo state :P. It's also sometimes randomly exiting, no error message... but I believe its related to this issue.

**Comment by Tricky1975** [comment]
This issue is also reported again on the forum, and he even says he knows about the "supposed fix" but that the bug still persists on his system: http://gamejolt.com/community/forums/topics/currently-playing/14494

**Comment by YLivay** [comment]
Heya! Can you run the client from the command line?
This way it'll print out logs you can attach to this issue so we'd know exactly whats up!

On Windows hit `Winkey + R` and type `cmd` to open up the command prompt. Then drag the game jolt executable into it. Make sure you close it from the tray before doing all this to make sure it actually opens up the new client.

**Comment by edwoodgrant** [comment]
Hmm I ran the GameJolt client from the command line but it doesn't print anything. Maybe it leaves a log file somewhere?

I ran both the quick access and the exe itself. but it doesn't print anything in the command line.

![gj_cmd](https://cloud.githubusercontent.com/assets/7331031/12272617/6db1edb4-b92f-11e5-9129-57d9631f0e35.png)

**Comment by Tricky1975** [comment]
I guess this is because Windows != Linux
Mostly when you start up a GUI app from the prompt this will happen in Windows.

**Comment by YLivay** [comment]
Ah, right. Sorry - in a production build, you wont get logs like this.
Need to add a way to have users share their logs built in the client.

**Comment by Tricky1975** [comment]
Well, perhaps a file that stores the log of the latest session? Or a file that keeps the log of the past few days? Or will these files get "too big" too soon?

**Comment by YLivay** [comment]
When we get tasty logs from https://github.com/gamejolt/issue-tracker/issues/495 we'll be able to resolve this completely!

**Comment by YLivay** [comment]
Yo! Can you please see if this issue persists in the newer version? If it does send us a system report by choosing "Send System Report" in the footer in the right side

**Comment by YLivay** [comment]
Got a system report, can finally see the problem!
This is related to log#10. Will be fixed for next version :)

**Comment by YLivay** [comment]
Got another log#25 thats relevant to this.

**Comment by Fappp** [comment]
This is gone for me with the latest update. Console does throw an error: "Process doesn't exist anymore" when shutting games down.

**Comment by YLivay** [comment]
Haha well dont write this issue off yet, its not solved fully!
As for that log line, it's perfectly fine, we throw that so we could catch it in the component that renders the game page to tell it to not play the game anymore :)

We'll update here when its fully resolved, thanks for the feedback!

**Comment by TastyGravy** [comment]
Try to uninstall the files by clicking the ... and then browse local files. delete the folder for the bad game then reinstall it. worked for me

**Comment by YLivay** [comment]
This is now solved :)

**Comment by lee222cyster** [comment]
I just had this issue how do I fix it Please
![image](https://user-images.githubusercontent.com/36343779/36066896-c127e5fc-0eaa-11e8-8082-a34a9e9c4aef.png)

**Comment by Tricky1975** [comment]
Maybe by waiting. The client auto-updates, but it needs time fore that and the bug remains active until the update is finished. Are you sure you got the latest version (and did @YLivay already push the new update, as the bug will also remain until he did. All he said is that the bug itself is fixed, but until Yariv pushed it and after that your client updated everything, you will "suffer").

**Comment by lee222cyster** [comment]
i have the 0.13.2 version

**Comment by Tricky1975** [comment]
@YLivay Did you already push this? If not reinstalling will be pointless, you know! (which I already tried to point out in my earlier post).

**Comment by lee222cyster** [comment]
how can i get in touch with @YLivay then so i can ask him

**Comment by Tricky1975** [comment]
He's notified every time you mention him... Since I mentioned him twice and you did once he's bound to know now we need him, so he should know

**Comment by lee222cyster** [comment]
I will wait and see if he responds

**Comment by lee222cyster** [comment]
@Tricky1975 @YLivay I have found my own way to fix the issue by the following:
1. uninstall game jolt client
2. delete all game jolt folders
3. reinstall game jolt
4. game still running fixed 
follow it in order and it will work for any of you

**Comment by BennyJets3** [comment]
I have the same issue too and it's still not fixed.
