### ISSUE TITLE
Cant click Download on website

### ISSUE THREAD

**Issue by BlackNinjaDK** [gamejolt/issue-tracker#583]
When i click download on the website it just refresh the site ( Like F5 ) and wont download.
It dosent matter what browser i am using.
I have Windows 8.1 64 bit.
Can someone send me a direct link so i dont have to click on the download botton :).

Thanks...

**Comment by BlackNinjaDK** [comment]
![image](https://cloud.githubusercontent.com/assets/17253654/13052368/cabc6a9a-d3fe-11e5-9997-666c1108146c.png)

**Comment by YLivay** [comment]
Can you try again now?

**Comment by YLivay** [comment]
Oh, yeah haha, we fudged up download URL.
You can get it from here for now https://n3b6p5n5.ssl.hwcdn.net/data/client/releases/v0.3.0/GameJoltClientSetup.exe
It'll be fixed in a few hours probably.

Sorry!

**Comment by BlackNinjaDK** [comment]
@YLivay I still cant click the download link :/.
But your link worked fine :). 
Thanks man :dancers:

**Comment by hworld** [comment]
Fixed. A bad url was pushed out for the download and I was flying sadly.
