### ISSUE TITLE
Forum - can't post new message - Reimplment spam approval

### ISSUE THREAD

**Issue by CyberKiller40** [gamejolt/issue-tracker#619]
Pretty randomly it happens that I can't post a new message (or a new thread) in the forum. I enter what I have to say, click add, then I see the blue loading bar at the top of the page go to the right and instead of the page reloading and showing my posted message, nothing more happens.

This happened while using Firefox, but I just tried in another browser (webkit based) and it looks the same. At the same time I can add replies to a different thread, but posting where it didn't work still doesn't work :-P.

**Comment by YLivay** [comment]
This is mostly likely because of the tests we've been doing with the chat potentially causing the db to slow down. It should be fixed by now! Closing this for now, if it happens again i'll reopen :)

**Comment by CyberKiller40** [comment]
It just happened again. Maybe I'm just banned from posting? My ip: 94.42.83.62

**Comment by CyberKiller40** [comment]
I tried again, another machine, another net connection, still can't post a new topic.

But maybe it's something else... Maybe there are some keywords that trigger this? :-P I want to write a topic about demos, greenlight and commercial games - maybe it's banned to write these words? :-P

**Comment by YLivay** [comment]
Hahaha amusing, it can very well be that!
Can you post what you're trying to send?
I'll see if it triggers the spam filters.

**Comment by CyberKiller40** [comment]
Here:
http://0bin.net/paste/UAETE8kH3tD08gik#ZulXKQC-YsWY2LqVbKbN5p3hMeQ4WN7POiYtjkQfovB
(it's mildly aggressive, but I'm annoyed by this situation, that's why I wanted to write about it)

**Comment by YLivay** [comment]
Haha we used to have auto detected spam posts await for approval but we kinda it with new forums. Machine learning isnt as op as we thought! I'm logging an issue for this but I cant guarantee when we'll actually tackle this S:

Good point in the post tho, personally I agree, and  there IS a plan in motion to remedy this too!

For now can you just try changing some words around (sorry for the monkey-tier temp solution)

**Comment by CyberKiller40** [comment]
I tried changing some of the words but it's hard without knowing which are the ones getting the post blocked. I'll just wait until it's possible to post it normally, if it will still be relevant then.

**Comment by YLivay** [comment]
@hworld you recently fixed that, right?

**Comment by hworld** [comment]
K, so the way it works now is that you are able to submit a forum topic/post. If it marks as spam it will let you know and the post won't show on the site. We go through these spam posts multiple times a day and approve any that shouldn't be there. Then the post will show.

If you edit, it will let the edit through, I believe. It should just mark it as spam so that we can catch any spam edits.
