### ISSUE TITLE
Frozen installation on Gamejolt

### ISSUE THREAD

**Issue by blazer3030** [gamejolt/issue-tracker#868]
Yes - I do see that this issue has technically been resolved (#545), but it appears to have returned.

I tried installing a game, and I'm not sure what happened but the buttons to stop/cancel are broken, and it's stuck at 0%. I'm running Windows 10 Home, and every other game installs just fine (including the earlier version of this game). This one glitched and I can't stop the download or complete it. Here's a snap:

http://imgur.com/a/Z5y50  

Since everything else is okay, my guess is that this is rare. It may have been because I started the download and X'd out of the program fairly quickly.

**Comment by hworld** [comment]
We will be pushing a client update that should fix this issue tomorrow. Will update here when it's out so you can tell us if it's resolved or not.

**Comment by YLivay** [comment]
Hey hey, we pushed the fix - can you test again to see if it works for you now? Thanks!

**Comment by blazer3030** [comment]
Hi again! It's still not working, but I'm not sure if I've received the update. My GJ is v0.3.3. The buttons to cancel and pause are still broken.

**Comment by YLivay** [comment]
Yes it does, odd that it didn't auto update for you before haha

**Comment by blazer3030** [comment]
Well okay. Thank you kindly devs!
